// version.h
#define MAJOR_NUMBER 5
#define MINOR_NUMBER 8
#define BUILD_NUMBER 5
#define BUILD_NUMBER_STRING "5"
#define VERSION_NUMBER_STRING "5.85"
#define FULL_VERSION_NUMBER_STRING "5.85"

#define SAFE_VERSION_NUMBER_STRING "585"
#define SAFE_FULL_VERSION_NUMBER_STRING "585"
#define COMPANY_NAME "The Eraser Project"
