// version.h
#define MAJOR_NUMBER 5
#define MINOR_NUMBER 8
#define BUILD_NUMBER 8
#define VERSION_NUMBER_STRING "5.88a"
#define FULL_VERSION_NUMBER_STRING "5.88a"

#define SAFE_VERSION_NUMBER_STRING "5.88a"
#define SAFE_FULL_VERSION_NUMBER_STRING "5.88a"
#define COMPANY_NAME "The Eraser Project"
