// version.h
#define MAJOR_NUMBER 5
#define MINOR_NUMBER 8
#define BUILD_NUMBER 7
#define VERSION_NUMBER_STRING "5.87.1"
#define FULL_VERSION_NUMBER_STRING "5.87.1"

#define SAFE_VERSION_NUMBER_STRING "587-beta1"
#define SAFE_FULL_VERSION_NUMBER_STRING "587-beta1"
#define COMPANY_NAME "The Eraser Project"
