// version.h
#define MAJOR_NUMBER 5
#define MINOR_NUMBER 8
#define BUILD_NUMBER 6
#define BUILD_NUMBER_STRING "6"
#define VERSION_NUMBER_STRING "5.86.1"
#define FULL_VERSION_NUMBER_STRING "5.86.1"

#define SAFE_VERSION_NUMBER_STRING "586-pl1"
#define SAFE_FULL_VERSION_NUMBER_STRING "586-pl1"
#define COMPANY_NAME "The Eraser Project"
